name: GitHub Actions Demo
run-name: Build the simple chalice webapp
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the build
        run: |
          rm -rf venv
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
          venv/bin/py.test
