name: GitHub Actions Demo
run-name: Build the simple chalice webapp
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the build
        run: |
          rm -rf venv
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
          venv/bin/py.test
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: chalice deploy
        uses: jayef0/chalice-extended-action@release-v0.2.1
        env:
          OPERATION: deploy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
